config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#index'
  get 'pages/index'

  get "/railshero" => redirect("https://railshero.pw")
  get "/blogpost" => redirect("https://railshero.pw/416/seo-friendly-urls-with-friendly_id")

  resources :posts
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :slug, use: :slugged


  #Validations are necessary.
  
  validates :slug, presence: true # Validates Presence i.e Slug can't be blank.

  validates :slug, uniqueness: true # Validates uniqueness i.e every slug must be unique.

  validates :slug, length: { in: 2..2000 } # Validates length i.e min & max length of the slug.

  validates :slug, format: { with: /\A[a-zA-Z0-9-_]+\z/,
    message: ":only letters(A-Z or a-z), numbers(0-9), dashes(-) and underscores(_) are allowed" } # Validates format of the slug.

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description, :slug)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_footer.html.erb
<hr style="color:red;">
<h4><%= link_to "Home", root_path %> | 
Friendly_ID Demo App by <%= link_to image_tag("/assets/logo-small.png"), blogpost_path, target: "_blank" %>
</h4>

app/views/layouts/_header.html.erb
<% if controller_name == "posts" && action_name == "show" %>
<div id="right">
<%= image_tag("/assets/slug-arrow.png", style: "width:44px;") %>
</div>
<% end %>

<div>
<h1>Friendly_ID Demo App</h1>
<p>Read More about friendly ID in this post, by <%= link_to "clicking here", blogpost_path, target: "_blank" %></p>
<%= link_to image_tag("/assets/wide-post-friendly.png", style: "width:99%;"), blogpost_path, target: "_blank" %>
<hr style="color:red;">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Friendly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/index.html.erb
<h4>Demo Blog Post App</h4>

<ul>
	<li>You can create Demo Posts by clicking on 'New Post'</li>
	<li>Or view existing posts by clicking on 'All Posts'</li>
	<li>Friendly id slugs are added as :slug to the posts table</li>
	<li>Validations are also added for the slugs so that the URLs don't break(i.e the slug must be present and only alphanumeric characters(A-Z or a-z & 0-9) along with dashes(-) and underscores(_) are allowed for the slugs); with a max length of 2000 characters.</li>
	<li>You can also change/modify the existing slugs/permalink(that you've added) in this demo app, but keep in mind that changing permalinks in real world public applications(i.e in production) may cause SEO to break, i.e; your app will work fine, but SEO will not.</li>
	<li>Please check out <%= link_to "railshero.pw", railshero_path, target: "_blank" %> for more posts</li>
</ul>

<br>
<%= link_to "All Posts", posts_path %>
<%= link_to "New Post", new_post_path %>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :slug %>
    <%= form.text_field :slug %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Slug</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= truncate(post.description, :length => 80) %></td>
        <td><%= post.slug %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @post.slug %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>